$files = Get-ChildItem "C:\Users\SOPORTES JPVM\Documents\web uci vet con seo\servicios\*.html"

foreach ($file in $files) {
    $content = Get-Content $file.FullName -Raw
    
    $content = $content -replace '\\u00ed', 'í'
    $content = $content -replace '\\u00f3', 'ó'
    $content = $content -replace '\\u00e1', 'á'
    $content = $content -replace '\\u00e9', 'é'
    $content = $content -replace '\\u00fa', 'ú'
    $content = $content -replace '\\u00f1', 'ñ'
    $content = $content -replace '\\u00ED', 'Í'
    $content = $content -replace '\\u00D3', 'Ó'
    $content = $content -replace '\\u00C1', 'Á'
    $content = $content -replace '\\u00C9', 'É'
    $content = $content -replace '\\u00DA', 'Ú'
    $content = $content -replace '\\u00D1', 'Ñ'
    
    $content = $content -replace 'Oncolog\\u00ia', 'Oncología'
    $content = $content -replace 'Cardiolog\\u00ia', 'Cardiología'
    $content = $content -replace 'Citopatolog\\u00ia', 'Citopatología'
    $content = $content -replace 'Dermatolog\\u00ia', 'Dermatología'
    $content = $content -replace 'Gastroenterolog\\u00ia', 'Gastroenterología'
    $content = $content -replace 'Nefrolog\\u00ia', 'Nefrología'
    $content = $content -replace 'Neurolog\\u00ia', 'Neurología'
    $content = $content -replace 'Nutrici\\u00f3n Cl\\u00ednica', 'Nutrición Clínica'
    $content = $content -replace 'Oncolog\\u00ia', 'Oncología'
    $content = $content -replace 'Ortopedia y Traumatolog\\u00ia', 'Ortopedia y Traumatología'
    $content = $content -replace 'Radiolog\\u00ia y Diagn\\u00f3stico', 'Radiología y Diagnóstico'
    $content = $content -replace 'Cardiolog\\u00ia', 'Cardiología'
    $content = $content -replace 'Citopatolog\\u00ia', 'Citopatología'
    $content = $content -replace 'Dermatolog\\u00ia', 'Dermatología'
    $content = $content -replace 'Gastroenterolog\\u00ia', 'Gastroenterología'
    $content = $content -replace 'Nefrolog\\u00ia', 'Nefrología'
    $content = $content -replace 'Neurolog\\u00ia', 'Neurología'
    $content = $content -replace 'Nutrici\\u00f3n Cl\\u00ednica', 'Nutrición Clínica'
    $content = $content -replace 'Oncolog\\u00ia', 'Oncología'
    $content = $content -replace 'Ortopedia y Traumatolog\\u00ia', 'Ortopedia y Traumatología'
    $content = $content -replace 'Radiolog\\u00ia y Diagn\\u00f3stico', 'Radiología y Diagnóstico'
    $content = $content -replace 'Cardiolog\\u00ia', 'Cardiología'
    $content = $content -replace 'Citopatolog\\u00ia', 'Citopatología'
    $content = $content -replace 'Dermatolog\\u00ia', 'Dermatología'
    $content = $content -replace 'Gastroenterolog\\u00ia', 'Gastroenterología'
    $content = $content -replace 'Nefrolog\\u00ia', 'Nefrología'
    $content = $content -replace 'Neurolog\\u00ia', 'Neurología'
    $content = $content -replace 'Nutrici\\u00f3n Cl\\u00ednica', 'Nutrición Clínica'
    $content = $content -replace 'Oncolog\\u00ia', 'Oncología'
    $content = $content -replace 'Ortopedia y Traumatolog\\u00ia', 'Ortopedia y Traumatología'
    $content = $content -replace 'Radiolog\\u00ia y Diagn\\u00f3stico', 'Radiología y Diagnóstico'
    
    $content = $content -replace 'Cardiolog\\u00ia Veterinaria', 'Cardiología Veterinaria'
    $content = $content -replace 'Citopatolog\\u00ia Veterinaria', 'Citopatología Veterinaria'
    $content = $content -replace 'Dermatolog\\u00ia Veterinaria', 'Dermatología Veterinaria'
    $content = $content -replace 'Gastroenterolog\\u00ia Veterinaria', 'Gastroenterología Veterinaria'
    $content = $content -replace 'Nefrolog\\u00ia Veterinaria', 'Nefrología Veterinaria'
    $content = $content -replace 'Neurolog\\u00ia Veterinaria', 'Neurología Veterinaria'
    $content = $content -replace 'Nutrici\\u00f3n Cl\\u00ednica Veterinaria', 'Nutrición Clínica Veterinaria'
    $content = $content -replace 'Oncolog\\u00ia Veterinaria', 'Oncología Veterinaria'
    $content = $content -replace 'Ortopedia y Traumatolog\\u00ia Veterinaria', 'Ortopedia y Traumatología Veterinaria'
    $content = $content -replace 'Radiolog\\u00ia y Diagn\\u00f3stico', 'Radiología y Diagnóstico'
    
    $content = $content -replace 'Ecocardiograf\\u00ia Doppler', 'Ecocardiografía Doppler'
    $content = $content -replace 'Diagn\\u00f3stico microsc\\u00f3pico', 'Diagnóstico microscópico'
    $content = $content -replace 'Diagn\\u00f3stico y tratamiento', 'Diagnóstico y tratamiento'
    $content = $content -replace 'tratamiento oncol\\u00f3gico', 'tratamiento oncológico'
    $content = $content -replace 'Ecocardiograf\\u00ia', 'Ecocardiografía'
    $content = $content -replace 'microsc\\u00f3pico', 'microscópico'
    $content = $content -replace 'oncol\\u00f3gico', 'oncológico'
    $content = $content -replace 'Diagn\\u00f3stico', 'Diagnóstico'
    $content = $content -replace 'oncol\\u00f3gico', 'oncológico'
    
    Set-Content $_.FullName $content -Encoding UTF8
}